version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    target-branch: "dev"
    labels:
      - "dependencies"
      - "security"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
